In [44]:
import pandas as pd
import numpy as np

In [45]:
df_2022 = pd.read_parquet("../data/2022_customer_data.parquet")
df_2022.describe()

,customer_id,first_purchase_date,last_purchase_date,total_spent,transaction_count
count,32423.000000,32423,32423,3.242300e+04,32423.000000
mean,49840.852512,2022-02-14 09:52:40.340691968,2022-05-23 10:45:21.507487744,3.153226e+06,5.741665
min,3.000000,2022-01-01 00:01:19.351042,2022-01-01 00:20:11.202473,2.188500e+04,1.000000
25%,24725.500000,2022-01-11 10:52:47.938606336,2022-04-18 14:11:07.944944640,5.112935e+05,1.000000
50%,49742.000000,2022-01-29 08:34:32.787824896,2022-06-08 05:14:02.179607040,1.512904e+06,3.000000
75%,74937.500000,2022-03-05 17:26:55.404736512,2022-07-06 16:54:45.602996224,3.974294e+06,7.000000
max,99998.000000,2022-07-31 23:59:03.408424,2022-07-31 23:59:19.821469,9.027193e+07,135.000000
std,28974.945290,NaN,NaN,4.364711e+06,7.071169

In [46]:
df_2022.head()

,customer_id,first_purchase_date,last_purchase_date,total_spent,transaction_count
0,3,2022-01-09 13:03:15.844494,2022-06-26 15:41:52.844494,2998828.0,7
1,8,2022-02-28 21:54:59.656991,2022-05-15 22:46:22.656991,1521320.0,2
2,9,2022-01-14 04:33:14.421034,2022-05-28 08:44:32.421034,906635.0,3
3,11,2022-03-07 14:29:13.759159,2022-03-07 14:29:13.759159,197533.0,1
4,15,2022-01-05 06:07:58.105040,2022-01-05 06:07:58.105040,73320.0,1

We'll apply the same cleaning steps as we did for the previous data

In [47]:
df_2022 = df_2022.sort_values(by="last_purchase_date").reset_index(drop=True)


df_2022["first_purchase_date"] = pd.to_datetime(df_2022["first_purchase_date"].dt.strftime("%Y-%m-%d %H:%M"))
df_2022["last_purchase_date"] = pd.to_datetime(df_2022["last_purchase_date"].dt.strftime("%Y-%m-%d %H:%M"))

# confirms avg_order_value calculation
df_2022["avg_order_value"] = (df_2022["total_spent"] / df_2022["transaction_count"]).round(3)


df_2022.rename(columns={"customer_age": "customer_tenure"}, inplace=True)
df_2022.rename(columns={"promo_code_used": "promo_usage_count"}, inplace=True)


CONVERSION_RATE = 16787.54   # This is the rate as of January 30 2026, can change ofc

df_2022["total_spent"] = (df_2022["total_spent"] / CONVERSION_RATE).round(3)
df_2022["avg_order_value"] = (df_2022["avg_order_value"] / CONVERSION_RATE).round(3)

In [48]:
df_2022.head()

,customer_id,first_purchase_date,last_purchase_date,total_spent,transaction_count,avg_order_value
0,68449,2022-01-01 00:20:00,2022-01-01 00:20:00,19.039,1,19.039
1,78745,2022-01-01 00:32:00,2022-01-01 00:32:00,43.349,1,43.349
2,37989,2022-01-01 01:27:00,2022-01-01 01:27:00,17.070,1,17.070
3,16051,2022-01-01 01:42:00,2022-01-01 01:42:00,15.703,1,15.703
4,74599,2022-01-01 01:49:00,2022-01-01 01:49:00,22.640,1,22.640

In [49]:
df_2022.to_csv("../data/processed/cleaned_2022_customer_data.parquet")